/**
 * Database types
 * 
 * This file will be generated by Prisma after running:
 * npx prisma generate
 * 
 * For now, this is a placeholder. After generating Prisma client,
 * you can import types from the generated Prisma client:
 * 
 * import type { Prisma } from '../generated/prisma';
 * export type Database = Prisma;
 */

// Placeholder - will be replaced after Prisma generation
export type Database = Record<string, never>;

