/**
 * Database Type Aliases for Web Package
 *
 * This file imports the Database type from @rare-find/shared and provides
 * convenient type aliases for commonly used table row types.
 *
 * The Database type itself is generated in @rare-find/shared and should be
 * regenerated when the Supabase schema changes:
 *   cd packages/shared && npm run db:generate-types
 */

import type { Database } from '@rare-find/shared';

// Re-export Database type for convenience
export type { Database };

// Type aliases for cleaner imports throughout the codebase
// These provide convenient names for Supabase autogenerated types

// Listing types
export type Listing = Database['public']['Tables']['listings']['Row']
export type ListingInsert = Database['public']['Tables']['listings']['Insert']
export type ListingUpdate = Database['public']['Tables']['listings']['Update']

// Recommendation types
export type Recommendation = Database['public']['Tables']['recommendations']['Row']
export type RecommendationInsert = Database['public']['Tables']['recommendations']['Insert']
export type RecommendationUpdate = Database['public']['Tables']['recommendations']['Update']

// SearchPreference types
export type SearchPreference = Database['public']['Tables']['search_preferences']['Row']
export type SearchPreferenceInsert = Database['public']['Tables']['search_preferences']['Insert']
export type SearchPreferenceUpdate = Database['public']['Tables']['search_preferences']['Update']

// AIEvaluation types
export type AIEvaluation = Database['public']['Tables']['ai_evaluations']['Row']
export type AIEvaluationInsert = Database['public']['Tables']['ai_evaluations']['Insert']
export type AIEvaluationUpdate = Database['public']['Tables']['ai_evaluations']['Update']

// User types
export type User = Database['public']['Tables']['users']['Row']
export type UserInsert = Database['public']['Tables']['users']['Insert']
export type UserUpdate = Database['public']['Tables']['users']['Update']

// Notification types
export type Notification = Database['public']['Tables']['notifications']['Row']
export type NotificationInsert = Database['public']['Tables']['notifications']['Insert']
export type NotificationUpdate = Database['public']['Tables']['notifications']['Update']

// Re-export utility types from @rare-find/shared (generated in database.ts)
export type {
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  CompositeTypes,
} from '@rare-find/shared';
export { Constants } from '@rare-find/shared';
